# Generated by Django 5.2.6 on 2025-10-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='population',
        ),
    ]
