# Generated by Django 5.2.6 on 2025-10-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_constituency_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constituency',
            old_name='county',
            new_name='district',
        ),
    ]
