# Generated by Django 5.2.6 on 2025-10-15 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_project_created_by_alter_project_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to='base.userprofile'),
        ),
    ]
