# Generated by Django 5.2.6 on 2025-10-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_projectcomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('not_started', 'Not Started'), ('planning', 'Planning'), ('in_progress', 'In Progress'), ('halfway', 'Halfway Done'), ('almost_done', 'Almost Done'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
