# Generated by Django 5.2.6 on 2025-10-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectupdate',
            name='update_type',
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('not_started', 'Not Started'), ('planning', 'Planning'), ('in_progress', 'In Progress'), ('halfway', 'Halfway Done'), ('almost_done', 'Almost Done'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
