# Generated by Django 5.2.6 on 2025-10-19 17:19

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_projectupdate_update_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(upload_to=base.models.project_document_upload_to),
        ),
    ]
