# Generated by Django 5.2.6 on 2025-10-21 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_projectdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='project_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='base.projectupdate'),
        ),
    ]
