# Generated by Django 5.2.6 on 2025-10-23 14:49

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_projectdocument_project_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=base.models.project_document_upload_to),
        ),
    ]
