# Generated by Django 5.2.6 on 2025-10-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_userprofile_cover_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, default='covers/default_cover.jpg', null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles/default_profile.jpg', null=True, upload_to='profiles/'),
        ),
    ]
