# Generated by Django 5.2.6 on 2025-11-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_userprofile_cover_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isDefaultPasswordChanged',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
