# Generated by Django 5.2.6 on 2025-11-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_project_status_alter_projectupdate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin'), ('officer', 'Officer')], default='viewer', max_length=20),
        ),
    ]
